main: me.redstonepvpcore.RedstonePvPCore
version: 2.0.3
name: RedstonePvPCore
author: Sandwicha
commands:
  redstonepvpcore:
    usage: /<command>
    description: Admin commands for RedstonePvPCore
    aliases: [rpcore, redpvpcore, rpc, redstonepvputils, rputils]
    permission: redstonepvpcore.admin
    permission-message: "You don't have permission to use this command."
  shop:
    usage: /<command> [other]
    description: Open shop GUI
    aliases: [shopmenu, mtgr, mtjr, b8alh, supermarket]
    permission: redstonepvpcore.shop
    permission-message: "You don't have permission to use this command."
  trash:
    usage: /<command> [other]
    description: Open trash menu
    aliases: [zbalh, zbalah, rubbishbin]
    permission: redstonepvpcore.trash
    permission-message: "You don't have permission to use this command."
permissions:
  redstonepvpcore.admin:
    description: Allows redstonepvpcore main command
    default: op
  redstonepvpcore.shop:
    description: Allows redstonepvpcore shop command
    default: true
  redstonepvpcore.shop.other:
    description: Allows redstonepvpcore shop other command
    default: op
  redstonepvpcore.trash:
    description: Allows redstonepvpcore trash command
    default: true
  redstonepvpcore.trash.other:
    description: Allows redstonepvpcore trash other command
    default: op